[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

[tool]
[tool.poetry]
authors = ["Your Name @Kostastsale"]
description = ""
name = "mitreattandckpy"
version = "0.1.0"
[tool.poetry.dependencies]
attackcti = "^0.3.1"
python = "^3.8"
[tool.poetry.dev-dependencies]
